name: CD

on:
  tag:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Déploiement
      - uses: ./.github/workflows/déploiement.yml

      - name: Livraison      
