name: CD

on:
  tag:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Déploiement
      - uses: ./.github/workflows/Déploiement.yml

      - name: Génération des notes de release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Notes de la release pour la version ${{ github.ref_name }}.
            - Liste des modifications
            - Nouveautés
          draft: false
          prerelease: false
