name: Intégration continue

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupère les fichiers
      - uses: actions/checkout@v4

      - name: Lint le code
      - uses: ./.github/workflows/super-lint.yml

      - name: Build et run image docker
      - uses: ./.github/workflows/docker-build.yml
        with:
          image-name: my-app
          dockerfile-path: ./Dockerfile

      - name: Test image docker
      - uses: ./.github/workflows/docker-test.yml

      - name: Vérification lint,build et test
